=== kansonkong/libatsc3/specs/atsc3/schemas/Schemas-for-A331-2017/AEAT-1.0-20170920.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:aeat="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/" targetNamespace="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="W3C/xml.xsd"/>
	<xs:element name="AEAT" type="aeat:AEATType"/>
	<xs:complexType name="AEATType">
		<xs:sequence>
			<xs:element name="AEA" type="aeat:AEAType" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="AEAType">
		<xs:sequence>
			<xs:element name="Header" type="aeat:headerType" minOccurs="0"/>
			<xs:element name="AEAText" type="aeat:langType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="LiveMedia" type="aeat:liveMediaType" minOccurs="0"/>
			<xs:element name="Media" type="aeat:mediaType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="aeaId" type="aeat:aeaIdType" use="required"/>
		<xs:attribute name="issuer" type="aeat:issuerType" use="required"/>
		<xs:attribute name="audience" type="aeat:audienceType" use="required"/>
		<xs:attribute name="aeaType" type="aeat:AEAtypeType" use="required"/>
		<xs:attribute name="refAEAId" type="xs:string"/>
		<xs:attribute name="priority" type="aeat:priorityType"/>
		<xs:attribute name="wakeup" type="xs:boolean" default="false"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="headerType">
		<xs:sequence>
			<xs:element name="EventCode" type="aeat:typeType" minOccurs="0"/>
			<xs:element name="EventDesc" type="aeat:langType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Location" type="aeat:locationType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="effective" type="xs:dateTime"/>
		<xs:attribute name="expires" type="xs:dateTime"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="typeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="langType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang" use="required"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="locationType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="aeat:locationTypeType" use="required"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="locationTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FIPS"/>
			<xs:enumeration value="SGC"/>
			<xs:enumeration value="polygon"/>
			<xs:enumeration value="circle"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="aeaIdType">
		<xs:restriction base="xs:string">
			<!-- TODO create regex -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="issuerType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="audienceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="public"/>
			<xs:enumeration value="restricted"/>
			<xs:enumeration value="private"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AEAtypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="alert"/>
			<xs:enumeration value="update"/>
			<xs:enumeration value="cancel"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="priorityType">
		<xs:restriction base="xs:unsignedByte">
			<xs:maxInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="liveMediaType">
		<xs:sequence>
			<xs:element name="ServiceName" type="aeat:langType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="bsid" type="aeat:listOfUnsignedShortType" use="required"/>
		<xs:attribute name="serviceId" type="xs:unsignedShort" use="required"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:simpleType name="listOfUnsignedShortType">
		<xs:list itemType="xs:unsignedShort"/>
	</xs:simpleType>
	<xs:complexType name="mediaType">
		<xs:sequence>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang"/>
		<xs:attribute name="mediaDesc" type="xs:string"/>
		<xs:attribute name="mediaType" type="aeat:mediaTypeType"/>
		<xs:attribute name="url" type="xs:anyURI" use="required"/>
		<xs:attribute name="alternateUrl" type="xs:anyURI"/>
		<xs:attribute name="contentType" type="xs:string"/>
		<xs:attribute name="contentLength" type="xs:unsignedLong"/>
		<xs:attribute name="mediaAssoc" type="xs:anyURI"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:simpleType name="mediaTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EventDescAudio"/>
			<xs:enumeration value="AEAtextAudio"/>
			<xs:enumeration value="EventSymbol"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== kansonkong/libatsc3/specs/atsc3/schemas/Schemas-for-A331-2017/AEAT-example-school-lockdown-update-20170920.xml
<AEAT xmlns="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/ AEAT-1.0-20170920.xsd">
	<AEA aeaId="AEA-2017020314005003" issuer="KUSR-TV" audience="public" aeaType="update" refAEAId="AEA-2017020313452000" priority="3" wakeup="false">
		<Header effective="2017-02-28T14:00:00.000-07:00" expires="2016-09-11T21:00:00.000-07:00">
			<EventDesc xml:lang="en">School Lockdown</EventDesc>
			<Location type="FIPS">22012</Location>
			<Location type="polygon">51.625,-76.0003 50.5157,-75.9998 51.6578,-79.1401 51.6129,-78.921 51.625,-76.0003</Location>
		</Header>
		<AEAText xml:lang="en">Update: Authorities have confirmed a shooting incident occurred [approximate time] at [building/location]. Police are on the scene and investigating. A suspect is NOT in custody. If you are campus on follow lockdown procedures, go into the nearest room and lock doors.  Persons not on campus are advised to stay away. Contact Campus Public Safety (Public Safety Campus phone number) if you see anything suspicious or have information. Wait for the all clear from officials or local authorities. For additional information and updates go to (Emergency Website) or stay tuned to (channel) </AEAText>
		<LiveMedia bsid="47 23" serviceId="3">
			<ServiceName xml:lang="en">KUSR</ServiceName>
		</LiveMedia>
		<Media xml:lang="en" mediaDesc="Message Audio English" mediaType="AEAtextAudio" url="AEAtextAudio/AEAtextAudio-en.mp3" contentType="audio/mp3" contentLength="301024" mediaAssoc="http://www.collegecampus.com/lockdowninstructions.png"/>
	</AEA>
</AEAT>

=== kansonkong/libatsc3/specs/atsc3/schemas/Schemas-for-A331-2017/AEAT-Example-20170920.xml
<?xml version="1.0" encoding="UTF-8"?>
<AEAT
	xmlns="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation= "tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/ AEAT-1.0-20170920.xsd">
	<AEA aeaId="3" issuer="KUSR" audience="public" aeaType="update" refAEAId="3" priority="3" wakeup="true">
		<Header effective="2016-09-11T13:00:00.000-07:00" expires="2016-09-11T16:00:00.000-07:00">
			<EventCode type="SAME">EVI</EventCode>
			<EventDesc xml:lang="en">Tornado Warning</EventDesc>
			<Location type="FIPS">000000</Location>
		</Header>
		<AEAText xml:lang="en">Put your helmet on</AEAText>
		<LiveMedia bsid="47 23" serviceId="3">
			<ServiceName xml:lang="en">KUSR</ServiceName>
		</LiveMedia>
		<Media xml:lang="en" mediaDesc="Evacuation Map" mediaType="AEAtextAudio" url="http://kusr.com/MyMedia" alternateUrl="http://kusr.com/MyAlternateMedia" contentType="image/png" contentLength="1024" mediaAssoc="http://kusr.com"/>
	</AEA>
</AEAT>

=== kansonkong/libatsc3/specs/atsc3/schemas/Schemas-for-A331-2017/AEAT-example-tornado-alert-bilingual-20170920.xml
<AEAT xmlns="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/AEAT/1.0/ AEAT-1.0-20170920.xsd">
	<AEA aeaId="AEA-2016091113002100" issuer="KUSR-TV" audience="public" aeaType="alert" priority="3" wakeup="true">
		<Header effective="2016-09-11T13:00:00.000-07:00" expires="2016-09-11T16:00:00.000-07:00">
			<EventCode type="SAME">TOR</EventCode>
			<EventDesc xml:lang="en">Tornado Warning</EventDesc>
			<Location type="FIPS">20150</Location>
			<Location type="polygon">51.625,-76.0003 50.5157,-75.9998 50.5157,-76 50.5157,-79.5137 50.7219,-79.514 51.4561,-79.5148 51.5319,-79.5821 51.5496,-79.5979 51.7137,-79.4165 51.7106,-79.192 51.6578,-79.1401 51.6129,-78.921 51.625,-76.0003</Location>
		</Header>
		<AEAText xml:lang="en">The National Weather Service has issued a Tornado Warning for Spark County.  A Tornado has been spotted on the ground 2 miles south of Smallville.  This tornado is moving Northeast at 40 MPH.  A Tornado is on the ground in the area of Smallville, Tinytown and Route 83. Take cover now. Move to an interior room on the lowest floor of a sturdy building.  Avoid windows.  Move to the closest shelter and protect yourself from flying debris.</AEAText>
		<AEAText xml:lang="es">El Servicio Meteorolo Nacional emitia Advertencia de Tornado para el Condado de Spark. Un Tornado se ha observado 2 millas al sur de Smallville. Este tornado se est oviendo hacia el noreste a 40 mph. Un tornado est n el suelo en la zona de Smallville, Tinytown y la ruta 83. Tome refugio ahora. Muse a una habitaci nterior en el piso bajo de un edificio robusto. Evite las ventanas. Muse al refugio cercano y protse de los desechos voladores.</AEAText>
		<LiveMedia bsid="47 23" serviceId="3">
			<ServiceName xml:lang="en">KUSR</ServiceName>
		</LiveMedia>
		<Media xml:lang="en" mediaDesc="Message Audio English" mediaType="AEAtextAudio" url="AEAtextAudio/AEAtextAudio-en.mp3" contentType="audio/mp3" contentLength="301024" mediaAssoc="http://kusr.com/tornadomap-en.png"/>
		<Media xml:lang="es" mediaDesc="Message Audio Spanish" mediaType="AEAtextAudio" url="AEAtextAudio/AEAtextAudio-es.mp3" contentType="audio/mp3" contentLength="302033" mediaAssoc="http://kusr.com/tornadomap-es.png"/>
	</AEA>
</AEAT>
